builders:
  sqflite_entities_generator:
    import: "package:sqflite_entities_generator/builder.dart"
    builder_factories: ["getBuilder"]
    build_extensions: {".dart": [".sql.g.dart"]}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]