name: postgres_entities_generator
description: postgres entities generator used for postgres_entities package
version: 0.0.1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  postgres_entities:
    path: ./../postgres_entities
  build: ^2.3.1
  build_runner: ^2.3.0
  source_gen: ^1.2.6
  analyzer: ^4.7.0

dev_dependencies:
  test:
  flutter_lints: ^2.0.1
