name: sqflite_entities_generator
description: sqflite entities generator used for sql_entities packages,  see more details on https://github.com/guid-empty/sqflite_entities
version: 0.0.3
repository: https://github.com/guid-empty/sqflite_entities_generator
homepage: https://github.com/guid-empty/sqflite_entities_generator

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  sqflite_entities: 0.0.3
  build: ^2.3.1
  build_runner: ^2.3.3
  source_gen: ^1.2.7
  analyzer: ^5.9.0

dev_dependencies:
  test:
  flutter_lints: ^2.0.1
