name: sqflite_entities_generator
description: sqflite entities generator used for sql_entities packages,  see more details on https://github.com/guid-empty/sqflite_entities
version: 0.1.0
homepage: https://github.com/guid-empty/sqflite_entities_generator
publish_to: http://pub.dev

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  build_runner: ^2.2.0
  source_gen: ^1.0.0
  analyzer: ^4.3.1
  build: ^2.0.0
  sqflite_entities: ^0.1.0

dev_dependencies:
  test:
  flutter_lints: ^2.0.1
